### PR TITLE
Revert "Rework stop-and-wait"

### PR DESCRIPTION
**Pull request by petermattis**
This reverts commit 777f15eeefa88b578853b565459b416af2fff228.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/234)

### CODE REVIEW

**Comment by petermattis** [comment]
Looks like this broke local acceptance tests. I don't see why and can't reproduce the breakage locally. I'm going to merge this without review with 🤞 that this fixes the problem.

**Comment by tschottdorf** [comment]
Thanks, was just noticing this.

**Comment by tschottdorf** [comment]
(I also don't get this behavior on osx, at least not deterministically, and it seems deterministic on the TC agents)

**Comment by petermattis** [comment]
Yep, reverting seems to have fixed the problem. Not sure what is going on. I'm unable to reproduce a failure on osx or on the builder on osx. I'll investigate more tomorrow.

**Comment by petermattis** [comment]
I'm not sure why https://github.com/cockroachdb/roachprod/commit/777f15eeefa88b578853b565459b416af2fff228 broke local acceptance tests on CI. So far I'm unable to reproduce any breakage. I've attempted both on osx and within the builder image on osx.

See https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=1000560&_focus=1491 for an example failure. It appears that `roachprod stop` is never returning. I'm speculating that something isn't working right with `kill -0`. @benesch Any thoughts?

**Comment by benesch** [comment]
No, I'm at a loss. All I have is to suggest that we move roachprod into cockroachdb/cockroach so that they're versioned together, both to make debugging this easier and to prevent changes to roachprod from breaking unrelated cockroach PRs.

**Comment by petermattis** [comment]
@benesch Did your suggestion? The roachtests are failing in the PR: https://teamcity.cockroachdb.com/viewLog.html?buildId=1009689&buildTypeId=Cockroach_UnitTests. Now to track down why.

**Pull request merged**
