### PR TITLE
Add workload-test subcommand for use in nightly tests

### PR DESCRIPTION
**Pull request by danhhz**
It runs a test configured by a `./workload run` command.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/35)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[main.go, line 579 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/35#-L4311NiihM8GI6JmOb7:-L4311NiihM8GI6JmOb8:b7ohrfx) ([raw file](https://github.com/cockroachdb/roachprod/blob/ef2a7ad733e5b7bfae268d51e232b7480a8adda0/main.go#L579)):*
> ```Go
> 
> var workloadTestCmd = &cobra.Command{
> 	Use:   "workload-test <cluster> <name> <workload-invocation>",
> ```

I wonder if we should fold this into the `test` command. Seems like the only addition is that we'd want to pass additional arguments on to the test function (e.g. `workloadTest`).

---

*[tests.go, line 492 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/35#-L430p85w476pNe4xFl6:-L430p85w476pNe4xFl7:b-xc8tnm) ([raw file](https://github.com/cockroachdb/roachprod/blob/ef2a7ad733e5b7bfae268d51e232b7480a8adda0/tests.go#L492)):*
> ```Go
> func workloadTest(clusterName, dir, name, cmd string) {
> 	var existing *testMetadata
> 	if dir != "" {
> ```

Being able to restart a performance test is pretty handy. Does the same apply to non-performance tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/roachprod/35)*

**Comment by danhhz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[main.go, line 579 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/35#-L4311NiihM8GI6JmOb7:-L431WYLQ6j2rhz2g6Yr:b-qlg93s) ([raw file](https://github.com/cockroachdb/roachprod/blob/ef2a7ad733e5b7bfae268d51e232b7480a8adda0/main.go#L579)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I wonder if we should fold this into the `test` command. Seems like the only addition is that we'd want to pass additional arguments on to the test function (e.g. `workloadTest`).
</blockquote></details>

I'd like to leave it separate while I'm iterating. Put a TODO though

---

*[tests.go, line 492 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/35#-L430p85w476pNe4xFl6:-L431TCkc5MmlwFL8D3j:bdyjsn0) ([raw file](https://github.com/cockroachdb/roachprod/blob/ef2a7ad733e5b7bfae268d51e232b7480a8adda0/tests.go#L492)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Being able to restart a performance test is pretty handy. Does the same apply to non-performance tests?
</blockquote></details>

Ha. I had this ripped out, but added it back in at the last second just to make it like the others. Easy to take back out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/roachprod/35)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests.go, line 492 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/35#-L430p85w476pNe4xFl6:-L433FDOVWWRK5PvG7vy:bnft7gn) ([raw file](https://github.com/cockroachdb/roachprod/blob/ef2a7ad733e5b7bfae268d51e232b7480a8adda0/tests.go#L492)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Ha. I had this ripped out, but added it back in at the last second just to make it like the others. Easy to take back out.
</blockquote></details>

I'm not at all sure what we want to do. Feel free to leave it for this PR, just realize it might be worth removing in the future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/roachprod/35#-:-L433aZrRY9aoEk99w-1:bnfp4nl)*

**Comment by danhhz** [comment]
TFTRs!

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests.go, line 492 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/35#-L430p85w476pNe4xFl6:-L434ElSAW_iCN0X-Sm4:btnwhhr) ([raw file](https://github.com/cockroachdb/roachprod/blob/ef2a7ad733e5b7bfae268d51e232b7480a8adda0/tests.go#L492)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not at all sure what we want to do. Feel free to leave it for this PR, just realize it might be worth removing in the future.
</blockquote></details>

May as well leave it out until we need it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/roachprod/35#-:-L434JCxfXDcxvFmJ3-E:bz5mair)*

**Pull request merged**
