### PR TITLE
Don't require SSH agent if GCE key exists

### PR DESCRIPTION
**Pull request by benesch**
Make it less painful to work with roachprod's SSH connections by always
attempting to authenticate with the default GCE key,
~/.ssh/google_compute_engine, if it exists.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/30)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[hosts.go, line 43 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/30#-L41pNULgPT1D56_xfKG:-L41pNULgPT1D56_xfKH:bex17rf) ([raw file](https://github.com/cockroachdb/roachprod/blob/398589fccbe903e4091c8799c321a5ac17e50784/hosts.go#L43)):*
> ```Go
> 		for _, vm := range c.VMs {
> 			// N.B. The username gcloud uses to log into instances is local
> 			// username, not than the Google account username.
> ```

The grammar in this comment is wonky.

---

*[ssh.go, line 106 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/30#-L41pxZgAk3BAl6B3OGs:-L41pxZhjawRrDxSjtBM:b-dm9o1u) ([raw file](https://github.com/cockroachdb/roachprod/blob/398589fccbe903e4091c8799c321a5ac17e50784/ssh.go#L106)):*
> ```Go
> var sshState = struct {
> 	sync.Mutex
> 	signers []ssh.Signer
> ```

Sort of strange that `signers` appears to be protected by the mutex, but then you access it without the mutex in `newSSHClient`. Perhaps you should use a `sync.Once` to initialize `signers` and move it out of this `sshState` struct (or reorganize the fields to make it clear that `sync.Mutex` only protects `clients`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/roachprod/30#-:-L41qDRNC05h2Yq81-Ky:bnfp4nl)*

**Comment by benesch** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[hosts.go, line 43 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/30#-L41pNULgPT1D56_xfKG:-L41xVydmntkpT0ocLyM:b-lq3l88) ([raw file](https://github.com/cockroachdb/roachprod/blob/398589fccbe903e4091c8799c321a5ac17e50784/hosts.go#L43)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The grammar in this comment is wonky.
</blockquote></details>

Yeesh, thanks.

---

*[ssh.go, line 106 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/30#-L41pxZgAk3BAl6B3OGs:-L41xX-qQVPOUbKfrf9Y:bwxbtfn) ([raw file](https://github.com/cockroachdb/roachprod/blob/398589fccbe903e4091c8799c321a5ac17e50784/ssh.go#L106)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Sort of strange that `signers` appears to be protected by the mutex, but then you access it without the mutex in `newSSHClient`. Perhaps you should use a `sync.Once` to initialize `signers` and move it out of this `sshState` struct (or reorganize the fields to make it clear that `sync.Mutex` only protects `clients`).
</blockquote></details>

Good point. Adjusted the struct to associate a `sync.Once` with `signers` and a `sync.Mutex` with `clients`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/roachprod/30)*

**Comment by petermattis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[ssh.go, line 125 at r2](https://reviewable.io:443/reviews/cockroachdb/roachprod/30#-L41y8x82TQTSuXjvGDp:-L41y8x82TQTSuXjvGDq:btvjprs) ([raw file](https://github.com/cockroachdb/roachprod/blob/0383e0b25ec0379a4ea5b94cbff93a8d6a82f803/ssh.go#L125)):*
> ```Go
> 
> 	sshState.signersInit.Do(func() {
> 		sshState.signers = []ssh.Signer{}
> ```

FYI, this line is unnecessary. Appending to a `nil` slice is fine. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/roachprod/30)*

**Comment by benesch** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[ssh.go, line 125 at r2](https://reviewable.io:443/reviews/cockroachdb/roachprod/30#-L41y8x82TQTSuXjvGDp:-L41yWQ5yoFL9cBkPZs2:b-72ce7h) ([raw file](https://github.com/cockroachdb/roachprod/blob/0383e0b25ec0379a4ea5b94cbff93a8d6a82f803/ssh.go#L125)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

FYI, this line is unnecessary. Appending to a `nil` slice is fine. 
</blockquote></details>

Good spot, thanks. It was necessary before, when `nil` meant initialized and `[]ssh.Signer{}` meant initialized w/o any authentication methods. `sync.Once` is much clearer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/roachprod/30)*

**Pull request merged**
