### PR TITLE
Add adminui subcommand

### PR DESCRIPTION
**Pull request by mjibson**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/77)

### CODE REVIEW

**Comment by benesch** [comment]
Can we call this `adminurl` for consistency with `pgurl`?

**Comment by mjibson** [comment]
Done.

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[main.go, line 765 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/77#-L5uS__Ammy894DwU-D_:-L5uS__BBmJDdG6H8O60:be8e2z9) ([raw file](https://github.com/cockroachdb/roachprod/blob/c0b68cf765665fc51b419d1b0f4d72ba25dd4f2d/main.go#L765)):*
> ```Go
> 			ip := c.VMs[node-1]
> 			port := install.GetAdminUIPort(c.Impl.NodePort(c, node))
> 			fmt.Printf("http://%s:%d/\n", ip, port)
> ```

This should be `https` if `secure` is true. Also, the `adminurl` command will need to take the `--secure` flag. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/roachprod/77)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[main.go, line 765 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/77#-L5uS__Ammy894DwU-D_:-L5uSrXsh_Y4nUTKSETH:b-snsljy) ([raw file](https://github.com/cockroachdb/roachprod/blob/c0b68cf765665fc51b419d1b0f4d72ba25dd4f2d/main.go#L765)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This should be `https` if `secure` is true. Also, the `adminurl` command will need to take the `--secure` flag. 
</blockquote></details>

Looks like the `pgurl` command also needs the `--secure` flag.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/roachprod/77)*

**Pull request merged**
