### PR TITLE
Increase SQL connection timeout delay

### PR DESCRIPTION
**Pull request by nvanbenschoten**
See https://github.com/cockroachdb/cockroach/issues/28369.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/187)

### CODE REVIEW

**Comment by benesch** [comment]
Roachprod always uses Bash, so we omit the /usr/bin/env everywhere.

**Comment by knz** [comment]
acknowledged, thanks for rexplaining

**Comment by knz** [comment]
Consider setting the env var to "0" to disable the timeout. This will make the client wait forever.

**Comment by nvanbenschoten** [comment]
> Consider setting the env var to "0" to disable the timeout. This will make the client wait forever.

Done.

**Pull request merged**
