### PR TITLE
Extract vm.Provider interface

### PR DESCRIPTION
**Pull request by bobvawter**
This ought to be the last refactoring change needed before adding AWS support.  If I did the job correctly, that should just be implementing a peer to the code in the gcloud package.

This change moves the management of VM instances into its own package and
encapsulates the existing gcloud integration behind a new vm.Provider
interface.

The VMOptions and associated flag handling for creating new VM instances is
shaken up a bit to allow providers to inject additional configuration options
that don't make sense to share (e.g. machine types, zones).

Misc changes:
* VersionSatisfies is moved into the install package, which is the only
  user of this function.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/78)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

This is certainly much cleaner separation of "local" clusters.

---

Review status: 0 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[vm/vm.go, line 95 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/78#-L5uMlY5KXfqIhHt67K3:-L5uMlY5KXfqIhHt67K4:b-2r0gv5) ([raw file](https://github.com/cockroachdb/roachprod/blob/5b6115a11253f3b234a44fbe7d3cad5da0a47775/vm/vm.go#L95)):*
> ```Go
> type ProviderFlags interface {
> 	// Configure a FlagSet with any options relevant to creating new vm instances.
> 	CreateFlags(*pflag.FlagSet)
> ```

Nit: I like the term in `Configure` as used in the comments, so perhaps `s/CreateFlags/ConfigureFlags/g`. This also removes ambiguity with the `Provider.Create` method. 

---

*[vm/gcloud/gcloud.go, line 21 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/78#-L5uM5dIaGDfAx_qech2:-L5uM5dIaGDfAx_qech3:b-ii2n5z) ([raw file](https://github.com/cockroachdb/roachprod/blob/5b6115a11253f3b234a44fbe7d3cad5da0a47775/vm/gcloud/gcloud.go#L21)):*
> ```Go
> const (
> 	project      = "cockroach-ephemeral"
> 	ProviderName = "gcloud"
> ```

Nit: should this be `"gce"`? `gcloud` is the tool. 

---

*[vm/local/local.go, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/78#-L5uMQhqqsUVQqdVfrAi:-L5uMQhqqsUVQqdVfrAj:b-5kim52) ([raw file](https://github.com/cockroachdb/roachprod/blob/5b6115a11253f3b234a44fbe7d3cad5da0a47775/vm/local/local.go#L7)):*
> ```Go
> 	"github.com/cockroachdb/roachprod/config"
> 	"github.com/cockroachdb/roachprod/install"
> 	"github.com/cockroachdb/roachprod/vm"
> ```

Are you using `goimports`? The ordering of the imports here is different than I'm used to. Not that it really matters as I almost never pay attention to this, just worried that future edits will result in import ordering fights.

---

*[vm/local/local.go, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/78#-L5uNlxeGb98I_4DvoMU:-L5uNlxeGb98I_4DvoMV:bnbcupa) ([raw file](https://github.com/cockroachdb/roachprod/blob/5b6115a11253f3b234a44fbe7d3cad5da0a47775/vm/local/local.go#L32)):*
> ```Go
> }
> 
> // No-op
> ```

`go lint` would complain about these doc comments not matching the standard if `// <function-name> ...`. For methods implementing an interface, we usually use a comment of the form:

```
// CleanSSH is part of the vm.Provider interface.
```

---

*[vm/local/local.go, line 98 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/78#-L5uNeT64Pw6w7j4GUuc:-L5uNeT64Pw6w7j4GUud:b-numljj) ([raw file](https://github.com/cockroachdb/roachprod/blob/5b6115a11253f3b234a44fbe7d3cad5da0a47775/vm/local/local.go#L98)):*
> ```Go
> 				Zone:      config.Local,
> 			})
> ```

Spurious blank line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/roachprod/78#-:-L5uNTQJOLG3EpDlPWoj:b20hwvs)*

**Comment by bobvawter** [comment]
Review status: 0 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[vm/vm.go, line 95 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/78#-L5uMlY5KXfqIhHt67K3:-L5uQoxUR9i-VHbBf5z7:b-a625z3) ([raw file](https://github.com/cockroachdb/roachprod/blob/5b6115a11253f3b234a44fbe7d3cad5da0a47775/vm/vm.go#L95)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: I like the term in `Configure` as used in the comments, so perhaps `s/CreateFlags/ConfigureFlags/g`. This also removes ambiguity with the `Provider.Create` method. 
</blockquote></details>

My intent here is to capture the flags needed for `roachprod create`.  I was trying to future-proof a bit in case a new command is added like `roachprod enlarge <instance-id> --gce-machine-type=evenBiggerSize` that needs additional flags.  That would have a corresponding `ProviderFlags.EnlargeFlags()` method added to the interface.  I'll update the documentation to be more clear about the intent.

---

*[vm/local/local.go, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/78#-L5uMQhqqsUVQqdVfrAi:-L5uS-V-zHdFyvx2mGTy:b-j3wtny) ([raw file](https://github.com/cockroachdb/roachprod/blob/5b6115a11253f3b234a44fbe7d3cad5da0a47775/vm/local/local.go#L7)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Are you using `goimports`? The ordering of the imports here is different than I'm used to. Not that it really matters as I almost never pay attention to this, just worried that future edits will result in import ordering fights.
</blockquote></details>

Fixed IDE configuration to fix grouping and also to run goimports on save.

---

*[vm/local/local.go, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/78#-L5uNlxeGb98I_4DvoMU:-L5uZQLJKrle-unmCYNp:b-896fix) ([raw file](https://github.com/cockroachdb/roachprod/blob/5b6115a11253f3b234a44fbe7d3cad5da0a47775/vm/local/local.go#L32)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`go lint` would complain about these doc comments not matching the standard if `// <function-name> ...`. For methods implementing an interface, we usually use a comment of the form:

```
// CleanSSH is part of the vm.Provider interface.
```
</blockquote></details>

Done.

---

*[vm/local/local.go, line 98 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/78#-L5uNeT64Pw6w7j4GUuc:-L5uSDKaPUxDAY7qhtts:bt2vr1b) ([raw file](https://github.com/cockroachdb/roachprod/blob/5b6115a11253f3b234a44fbe7d3cad5da0a47775/vm/local/local.go#L98)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Spurious blank line.
</blockquote></details>

Fixed.

---

*[vm/gcloud/gcloud.go, line 21 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/78#-L5uM5dIaGDfAx_qech2:-L5uRd0a_1fwETo7FHzZ:bpy3pja) ([raw file](https://github.com/cockroachdb/roachprod/blob/5b6115a11253f3b234a44fbe7d3cad5da0a47775/vm/gcloud/gcloud.go#L21)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: should this be `"gce"`? `gcloud` is the tool. 
</blockquote></details>

Will generally rename gcloud -> gce.  Shorter to type, too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/roachprod/78)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[main.go, line 23 at r2](https://reviewable.io:443/reviews/cockroachdb/roachprod/78#-L5v28WUUjs6Cv5TSxFv:-L5v28WUUjs6Cv5TSxFw:busdz1k) ([raw file](https://github.com/cockroachdb/roachprod/blob/7fcbc8620ed456721446989130787aa92bae8a02/main.go#L23)):*
> ```Go
> 	"github.com/cockroachdb/roachprod/vm"
> 	"github.com/cockroachdb/roachprod/vm/gce"
> 	"github.com/cockroachdb/roachprod/vm/local"
> ```

I think a few other files here need to be run through `goimports`. Probably worthwhile to run everything in the `roachprod` repo through as a separate commit (or separate PR).

---

*[vm/vm.go, line 95 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/78#-L5uMlY5KXfqIhHt67K3:-L5v1m8upozZMDgQYr4_:b-za9bj4) ([raw file](https://github.com/cockroachdb/roachprod/blob/5b6115a11253f3b234a44fbe7d3cad5da0a47775/vm/vm.go#L95)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

My intent here is to capture the flags needed for `roachprod create`.  I was trying to future-proof a bit in case a new command is added like `roachprod enlarge <instance-id> --gce-machine-type=evenBiggerSize` that needs additional flags.  That would have a corresponding `ProviderFlags.EnlargeFlags()` method added to the interface.  I'll update the documentation to be more clear about the intent.
</blockquote></details>

Ah, I misunderstood the method. I thought it was creating general purpose flags. Perhaps this should be named `ConfigureCreateFlags()`. Or leave as-is.

---

*[vm/vm.go, line 122 at r2](https://reviewable.io:443/reviews/cockroachdb/roachprod/78#-L5v2b4ixobudzPxwNh1:-L5v2b4ixobudzPxwNh2:b13mumf) ([raw file](https://github.com/cockroachdb/roachprod/blob/7fcbc8620ed456721446989130787aa92bae8a02/vm/vm.go#L122)):*
> ```Go
> 
> // Sequentially execute an action against all known VM Providers.
> func EachProvider(action func(Provider) error) error {
> ```

I'm not finding the names `EachProvider` and `ForProvider` to adequately capture the distinction between them. Sort of a nit, but perhaps one or the other should capture `sequential` (`seq`) or `parallel` in the name. On the other hand, the relative small number of usages of these functions is unlikely to lead to error, so feel free to push back if you think the current name is adequate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/roachprod/78#-:-L5v3cqSEktr6HKA7vsW:bnfp4nl)*

**Comment by bobvawter** [comment]
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[main.go, line 23 at r2](https://reviewable.io:443/reviews/cockroachdb/roachprod/78#-L5v28WUUjs6Cv5TSxFv:-L5xz7MVByppKHt2JPjg:bzhlgja) ([raw file](https://github.com/cockroachdb/roachprod/blob/7fcbc8620ed456721446989130787aa92bae8a02/main.go#L23)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think a few other files here need to be run through `goimports`. Probably worthwhile to run everything in the `roachprod` repo through as a separate commit (or separate PR).
</blockquote></details>

There were just two other files, tests.go and install.go that disagreed with goimports.  I've added them as a second commit.

---

*[vm/vm.go, line 95 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/78#-L5uMlY5KXfqIhHt67K3:-L5xw0g7DMt99UbLKr1F:b8zbtcg) ([raw file](https://github.com/cockroachdb/roachprod/blob/5b6115a11253f3b234a44fbe7d3cad5da0a47775/vm/vm.go#L95)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ah, I misunderstood the method. I thought it was creating general purpose flags. Perhaps this should be named `ConfigureCreateFlags()`. Or leave as-is.
</blockquote></details>

`ConfigureCreateFlags()` it is.

---

*[vm/vm.go, line 122 at r2](https://reviewable.io:443/reviews/cockroachdb/roachprod/78#-L5v2b4ixobudzPxwNh1:-L5xvM6lJuPOr7j4soBx:b-ra7d6x) ([raw file](https://github.com/cockroachdb/roachprod/blob/7fcbc8620ed456721446989130787aa92bae8a02/vm/vm.go#L122)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not finding the names `EachProvider` and `ForProvider` to adequately capture the distinction between them. Sort of a nit, but perhaps one or the other should capture `sequential` (`seq`) or `parallel` in the name. On the other hand, the relative small number of usages of these functions is unlikely to lead to error, so feel free to push back if you think the current name is adequate.
</blockquote></details>

Tweaked the names to ProvidersParallel and ProvidersSequential.  Eliminated EachProvider() in favor of ProvidersSequenial() plus a new AllProviderNames() method to reduce duplicate behavior.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/roachprod/78)*

**Comment by petermattis** [comment]
:shipit:

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/roachprod/78#-:-L5yeJiOymt-afrUkX81:b-xr9eiq)*

**Pull request merged**
