### PR TITLE
Run all commands with ROACHPROD=true

### LINKED ISSUE #60: `roachprod stop` kills too much
If running a local cluster, `roachprod stop cockroach` will terminate a running Cockroach build, not just the nodes in the cluster. Perhaps `killall` would work better than `pkill`?

### PR DESCRIPTION
**Pull request by tschottdorf**
and use this fact to kill the right processes in cluster.Stop().

Fixes #60.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/74)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm: that was easier than I expected.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[install/cluster_synced.go, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/74#-L5sI8YPiD-vkbkb8zhz:-L5sI8YPiD-vkbkb8zi-:b-xzmqps) ([raw file](https://github.com/cockroachdb/roachprod/blob/889d1d0e56906355adad83a7c22d1843c623858c/install/cluster_synced.go#L117)):*
> ```Go
> 		// NB: the awkward-looking `grep` invocation serves to avoid having the
> 		// grep process match its own output from `ps`.
> 		cmd := "ps axeww -o pid -o command | grep -E 'ROACHPROD=[a-z]+' | awk '{ print $1 }' | xargs kill -9 || true;"
> ```

Pro-tip, you can combine the `grep` and `awk`: `awk '/ROACHPROD=[a-z]+/ { print $1 }'`. Is there a reason you went for `ROACHPROD=[a-z]+` vs `ROACHPROD=true`?

---

*[install/cockroach.go, line 151 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/74#-L5sItxKBIzsMpyANReA:-L5sItxL7uHHYbWMjnPX:b-e78e15) ([raw file](https://github.com/cockroachdb/roachprod/blob/889d1d0e56906355adad83a7c22d1843c623858c/install/cockroach.go#L151)):*
> ```Go
> 		binary := cockroachNodeBinary(c, nodes[i])
> 		cmd := "mkdir -p " + logDir + "; " +
> 			"env ROACHPROD=true " +
> ```

I don't think the `env` is necessary here as we're running through bash. Should this addition be after `c.Env` so that the user can't override the setting?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/roachprod/74#-:-L5sJMHhuKA9e8-jcgdQ:b-ovhsao)*

**Comment by tschottdorf** [comment]
TFTRs!

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[install/cluster_synced.go, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/74#-L5sI8YPiD-vkbkb8zhz:-L5svwyRP3HToF-69Do2:b35x0hd) ([raw file](https://github.com/cockroachdb/roachprod/blob/889d1d0e56906355adad83a7c22d1843c623858c/install/cluster_synced.go#L117)):*
Switched to awk.

> Is there a reason you went for ROACHPROD=[a-z]+ vs ROACHPROD=true?

Yeah, there's a comment just above this line: not wanting the grep invocation itself to match. There might be a nicer way to the same end.

---

*[install/cockroach.go, line 151 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/74#-L5sItxKBIzsMpyANReA:-L5sxug1tKcLcr-imhW8:b-896fix) ([raw file](https://github.com/cockroachdb/roachprod/blob/889d1d0e56906355adad83a7c22d1843c623858c/install/cockroach.go#L151)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I don't think the `env` is necessary here as we're running through bash. Should this addition be after `c.Env` so that the user can't override the setting?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/roachprod/74#-:-L5sxvpk3ZwjAfMLyoxJ:bz5mair)*

**Comment by benesch** [comment]
:lgtm: modulo the one misspelling; take or leave the rest

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[install/cluster_synced.go, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/74#-L5sI8YPiD-vkbkb8zhz:-L5szS1DtJkc543QBfzy:b-eu1jzp) ([raw file](https://github.com/cockroachdb/roachprod/blob/889d1d0e56906355adad83a7c22d1843c623858c/install/cluster_synced.go#L117)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Switched to awk.

> Is there a reason you went for ROACHPROD=[a-z]+ vs ROACHPROD=true?

Yeah, there's a comment just above this line: not wanting the grep invocation itself to match. There might be a nicer way to the same end.
</blockquote></details>

`grep -E 'ROACHPROD=[t]rue'` is the traditional approach. Feel free to ignore.

---

*[install/cluster_synced.go, line 276 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/74#-L5szg9_KrYp1RlmakHx:-L5szg9_KrYp1RlmakHy:bw34a65) ([raw file](https://github.com/cockroachdb/roachprod/blob/889d1d0e56906355adad83a7c22d1843c623858c/install/cluster_synced.go#L276)):*
> ```Go
> 		defer session.Close()
> 
> 		nodeCmd := "env ROACHROD=true " + cmd
> ```

"ROACHROD"

Also I think you can drop the "env" here.

---

*[install/cluster_synced.go, line 415 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/74#-L5szjYHiyHCfULN879O:-L5szjYHiyHCfULN879P:bv1cw87) ([raw file](https://github.com/cockroachdb/roachprod/blob/889d1d0e56906355adad83a7c22d1843c623858c/install/cluster_synced.go#L415)):*
> ```Go
> 		urls = append(urls, c.Impl.NodeURL(c, ip, c.Impl.NodePort(c, nodes[i])))
> 	}
> 	return session.Run("ulimit -n 16384; env ROACHPROD=true " + cmd + " " + strings.Join(urls, " "))
> ```

I think `env` is unnecessary here, too.

---

*[install/cluster_synced.go, line 676 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/74#-L5sztQrzmoT0Mybiw2t:-L5sztQrzmoT0Mybiw2u:b-1kzc9c) ([raw file](https://github.com/cockroachdb/roachprod/blob/889d1d0e56906355adad83a7c22d1843c623858c/install/cluster_synced.go#L676)):*
> ```Go
> 	}
> 	if len(args) > 0 {
> 		allArgs = append(allArgs, "env", "ROACHPROD=true")
> ```

And here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/roachprod/74#-:-L5t-9g5_CsOmK4piWGm:b-qgyjtq)*

**Comment by tschottdorf** [comment]
TFTRs!

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[install/cluster_synced.go, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/74#-L5sI8YPiD-vkbkb8zhz:-L5wnO4ECMNQ4lwYmxnT:bnqjyde) ([raw file](https://github.com/cockroachdb/roachprod/blob/889d1d0e56906355adad83a7c22d1843c623858c/install/cluster_synced.go#L117)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

`grep -E 'ROACHPROD=[t]rue'` is the traditional approach. Feel free to ignore.
</blockquote></details>

That's better. Done.

---

*[install/cluster_synced.go, line 276 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/74#-L5szg9_KrYp1RlmakHx:-L5wnQpKgmLihAYAmggb:b-tmuyzt) ([raw file](https://github.com/cockroachdb/roachprod/blob/889d1d0e56906355adad83a7c22d1843c623858c/install/cluster_synced.go#L276)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

"ROACHROD"

Also I think you can drop the "env" here.
</blockquote></details>

:see_no_evil: 

---

*[install/cluster_synced.go, line 415 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/74#-L5szjYHiyHCfULN879O:-L5wnZOI83_fKxTJdmhC:b-896fix) ([raw file](https://github.com/cockroachdb/roachprod/blob/889d1d0e56906355adad83a7c22d1843c623858c/install/cluster_synced.go#L415)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I think `env` is unnecessary here, too.
</blockquote></details>

Done.

---

*[install/cluster_synced.go, line 676 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/74#-L5sztQrzmoT0Mybiw2t:-L5wngEEN-QGT9AgTCKC:b-896fix) ([raw file](https://github.com/cockroachdb/roachprod/blob/889d1d0e56906355adad83a7c22d1843c623858c/install/cluster_synced.go#L676)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

And here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/roachprod/74#-:-L5wnzKWYtk-6cmorxdr:bz5mair)*

**Pull request merged**
