### PR TITLE
Force chrony to synchronize

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/226)

### CODE REVIEW

**Comment by petermattis** [comment]
Unfortunately, this doesn't seem to work properly. After the `chronyc -a makestep`, the clocks are still not synchronized for a bit. Sending this out in the hopes that it nerd snipes one of you into tracking down why.

**Comment by mberhault** [comment]
I don't see `ntp` being disabled anywhere. Isn't it installed by default?

**Comment by petermattis** [comment]
@mberhault:

```
~ ps axuww | grep ntp
ubuntu    3632  0.0  0.0  12944   968 pts/0    S+   13:51   0:00 grep --color=auto ntp
```

**Comment by petermattis** [comment]
I think this is working now. The key was the use of `waitsync`. The output from that indicates that `chronyd` is often taking a few seconds to perform the synchronization.

**Comment by petermattis** [comment]
Ping. I'd like to merge this before tonight's nightly roachtest run.

**Pull request merged**
