### PR TITLE
Add encryption flag to allow roachproad start encrypted cluster

### PR DESCRIPTION
**Pull request by windchan7**
Added encryption at rest flag `--encrypt` to `roachprod start` to allow
encryption at rest to be used for each nodes.

Part of encryption at rest: #19783.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/170)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

Does this work if you `start --encrypt`, `stop`, then `start --encrypt` again? Seems like that will generate a new key, overwriting the old one.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[install/cockroach.go, line 338 at r1](https://reviewable.io/reviews/cockroachdb/roachprod/170#-LDMrJEI0ENEb26Gmf1A:-LDMrJEI0ENEb26Gmf1B:b-atoptk) ([raw file](https://github.com/cockroachdb/roachprod/blob/bc89f6ffcaf33536af47ffff3b36fbc71b856d82/install/cockroach.go#L338)):*
> ```Go
> 			encryptArgs := "--enterprise-encryption=path=%s,key=%s/aes-128.key,old-key=plain"
> 			var storeDir string
> 			if idx := argExists(extraArgs, "--store"); idx == -1{
> ```

Do you have `gofmt` turned on? Looks like there is a missing space at the end of this line.

---

*[install/cockroach.go, line 348 at r1](https://reviewable.io/reviews/cockroachdb/roachprod/170#-LDMqR2I8ZSFWWcOrnxR:-LDMqR2I8ZSFWWcOrnxS:b-f8ueib) ([raw file](https://github.com/cockroachdb/roachprod/blob/bc89f6ffcaf33536af47ffff3b36fbc71b856d82/install/cockroach.go#L348)):*
> ```Go
> 			// Command to create the store key.
> 			keyCmd = "openssl rand -out %s/aes-128.key 48; "
> 			keyCmd = fmt.Sprintf(keyCmd, storeDir)
> ```

Any reason you broke this over 2 lines? I think this is more naturally written as:

```
keyCmd = fmt.Sprintf("openssl rand -out %s/aes-128.key 48; ", storeDir)
```

Also, I would incorporate `dirCmd` into `keyCmd`. The 2 commands must always be used together:

```
keyCmd = fmt.Sprintf("mkdir -p %[1]s; openssl rand -out %[1]s/aes-128.key 48; ", storeDir)
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/170#-:-LDMqoK8DmXD3k0SixoG:b553o5v)*

**Comment by windchan7** [comment]
Sadly no as mentioned in the comment. Since right now we are only doing some basic benchmarking, I think it makes sense to leave it as a TODO.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/170#-:-LDMueMm4rS2P-u5Lchv:b-rd4hg6)*

**Comment by mberhault** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[install/cockroach.go, line 335 at r1](https://reviewable.io/reviews/cockroachdb/roachprod/170#-LDMuzA_7yU6UluCm495:-LDMuzA_7yU6UluCm496:bbq79rg) ([raw file](https://github.com/cockroachdb/roachprod/blob/bc89f6ffcaf33536af47ffff3b36fbc71b856d82/install/cockroach.go#L335)):*
> ```Go
> 			// Encryption at rest is turned on for the cluster.
> 			// If turned on, `roachprod start` will always start the nodes with new store keys
> 			// and the old-key set to be plain. So users need to ensure the start logic is correct.
> ```

Can you stick a TODO to allow specifying other key sizes? (or `plain`). It's a bit tedious across restarts as we'll have to test for existing keys, so this can wait.

---

*[install/cockroach.go, line 348 at r1](https://reviewable.io/reviews/cockroachdb/roachprod/170#-LDMqR2I8ZSFWWcOrnxR:-LDMuT0w6mCj6k-PaBx4:b-2e2ujf) ([raw file](https://github.com/cockroachdb/roachprod/blob/bc89f6ffcaf33536af47ffff3b36fbc71b856d82/install/cockroach.go#L348)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Any reason you broke this over 2 lines? I think this is more naturally written as:

```
keyCmd = fmt.Sprintf("openssl rand -out %s/aes-128.key 48; ", storeDir)
```

Also, I would incorporate `dirCmd` into `keyCmd`. The 2 commands must always be used together:

```
keyCmd = fmt.Sprintf("mkdir -p %[1]s; openssl rand -out %[1]s/aes-128.key 48; ", storeDir)
```
</blockquote></details>

We should reuse existing keys or restarts won't work. You could either wrap the openssl command in `if [ -e aes-128.key ]` (assuming bash is used for all execution), or write to a temporary file then `mv -f -n tmpfile aes-128.key` (does not clobber the destination if it exists).

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/170)*

**Comment by windchan7** [comment]
Never mind, Marc just gave a suggestion and I will add it.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/170#-:-LDMvd5S01oqrLG5-oyU:b-al6gb0)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[install/cockroach.go, line 348 at r1](https://reviewable.io/reviews/cockroachdb/roachprod/170#-LDMqR2I8ZSFWWcOrnxR:-LDMxs1EDh5JIPYe-Q9G:b-5hyal8) ([raw file](https://github.com/cockroachdb/roachprod/blob/bc89f6ffcaf33536af47ffff3b36fbc71b856d82/install/cockroach.go#L348)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

We should reuse existing keys or restarts won't work. You could either wrap the openssl command in `if [ -e aes-128.key ]` (assuming bash is used for all execution), or write to a temporary file then `mv -f -n tmpfile aes-128.key` (does not clobber the destination if it exists).
</blockquote></details>

Yes, bash is used for all command execution.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/170)*

**Comment by windchan7** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[install/cockroach.go, line 335 at r1](https://reviewable.io/reviews/cockroachdb/roachprod/170#-LDMuzA_7yU6UluCm495:-LDN2NgP9XbZqZSfTOwx:b-896fix) ([raw file](https://github.com/cockroachdb/roachprod/blob/bc89f6ffcaf33536af47ffff3b36fbc71b856d82/install/cockroach.go#L335)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

Can you stick a TODO to allow specifying other key sizes? (or `plain`). It's a bit tedious across restarts as we'll have to test for existing keys, so this can wait.
</blockquote></details>

Done.

---

*[install/cockroach.go, line 338 at r1](https://reviewable.io/reviews/cockroachdb/roachprod/170#-LDMrJEI0ENEb26Gmf1A:-LDN2NzR6lKfZ0YvI4Jl:b-896fix) ([raw file](https://github.com/cockroachdb/roachprod/blob/bc89f6ffcaf33536af47ffff3b36fbc71b856d82/install/cockroach.go#L338)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Do you have `gofmt` turned on? Looks like there is a missing space at the end of this line.
</blockquote></details>

Done.

---

*[install/cockroach.go, line 348 at r1](https://reviewable.io/reviews/cockroachdb/roachprod/170#-LDMqR2I8ZSFWWcOrnxR:-LDN2Odv5OYDVqKwELzV:b-896fix) ([raw file](https://github.com/cockroachdb/roachprod/blob/bc89f6ffcaf33536af47ffff3b36fbc71b856d82/install/cockroach.go#L348)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yes, bash is used for all command execution.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/170)*

**Comment by mberhault** [comment]
:lgtm:
Make sure to test it out, including with stop/start.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/170#-:-LDN4hN-26kRSlGR_G8O:b-uy5p9a)*

**Comment by windchan7** [comment]
Yep, I tested using my favorite upgrade roachtest. Seems to work fine for stop and start.

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[install/cockroach.go, line 348 at r1](https://reviewable.io/reviews/cockroachdb/roachprod/170#-LDMqR2I8ZSFWWcOrnxR:-LDNQ27o1xU3lcLA8Nke:b-phq0td) ([raw file](https://github.com/cockroachdb/roachprod/blob/bc89f6ffcaf33536af47ffff3b36fbc71b856d82/install/cockroach.go#L348)):*
<details><summary><i>Previously, windchan7 (Victor Chen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Rather than `if/else`, you can instead use `&&`. For example, `test ! -e aes-128.key && echo exists || echo not-exists`

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/170)*

**Pull request merged**
