### PR TITLE
Atomically write the hosts files when syncing hosts

### PR DESCRIPTION
**Pull request by petermattis**
The file lock acquired by syncAll prevents another process from syncing
the hosts file concurrently, but we don't acquire that lock while
reading the hosts files. This could lead to a concurrent reader seeing
an empty hosts file.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/183)

### CODE REVIEW

**Comment by benesch** [comment]
Oops. Good catch. 

I'm having trouble convincing myself this is correct, though. `loadClusters` reads all files in the hosts directory, so it's going to pick up these `.tmp` files. Maybe that's fine? But I think it might be cleaner to just acquire the flock in `loadClusters` instead of making each file write atomic.

**Comment by petermattis** [comment]
> I'm having trouble convincing myself this is correct, though. loadClusters reads all files in the hosts directory, so it's going to pick up these .tmp files. Maybe that's fine? But I think it might be cleaner to just acquire the flock in loadClusters instead of making each file write atomic.

`syncAll` is somewhat slow, though. I don't think it is a big problem that `loadClusters` sees the `.tmp` files. It will just create clusters with those file names. But also easy to skip those files.

**Comment by benesch** [comment]
SGTM

**Comment by petermattis** [comment]
I should mention for posterity that I discovered this issue because I'm running the `kv{0,95}` roachtests in a loop, back filling performance numbers for binaries over the course of the 2.1 release cycle. Before this change I would very quickly hit an error when creating a cluster where it appeared the cluster had 0 nodes. The relevant factor here was that I was running `roachtest run 'kv(0|95)/encrypt=false'`. This runs 4 tests concurrently and thus creates 4 clusters concurrently. After this change, I've successfully run 5 back fill iterations without incident.

**Pull request merged**
