### PR TITLE
Merge roachperf into roachprod

### PR DESCRIPTION
**Pull request by benesch**
Merge roachperf into roachprod. Roachprod is now a one-stop shop for
managing CockroachDB clusters.

Any invocation of roachperf is now a valid invocation of roachprod, with
the following caveats:

  * roachperf commands which took a cluster name as an argument, like
    `roachperf USER-CLUSTER start`, have been reordered. The equivalent
    roachprod command is `roachprod start USER-CLUSTER`.

  * To make room for roachper's status command, `roachprod status` has
    been renamed to `roachprod list`. The prior behavior of `roachprod
    list` is available as `roachprod list --details`.

In the interest of incremental improvement, this is the minimal change
necessary to make this merge possible. More cleanup is in order.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/26)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

If you care, in the commit message: `s/roachper's/roachperf's/g`

---

Review status: 0 of 19 files reviewed at latest revision, 7 unresolved discussions.

---

*[cassandra.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/26#-L3oCSB8WRMxEOppKFDL:-L3oCSB8WRMxEOppKFDM:bxsezil) ([raw file](https://github.com/cockroachdb/roachprod/blob/9b2344f9ca93b373d65a830609ce17cfca6afd67/cassandra.go#L80)):*
> ```Go
> 		// TODO(peter): This will require a bit of work to adjust ports in
> 		// cassandra.yaml.
> 		panic("unimplemented: local cassandra cluster")
> ```

I noticed after submitting that this breaks `roachprod status local`. Can you just delete this line?

---

*[main.go, line 562 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/26#-L3oCh_DWXIFhFphRHZE:-L3oCh_DWXIFhFphRHZF:bkxo5ny) ([raw file](https://github.com/cockroachdb/roachprod/blob/9b2344f9ca93b373d65a830609ce17cfca6afd67/main.go#L562)):*
> ```Go
> directory of a previous test. For example:
> 
> 	roachperf denim test kv_0.cockroach-6151ae1
> ```

`s/denim test/test denim/g`

---

*[main.go, line 761 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/26#-L3oCvCik9AWJpfs2weC:-L3oCvCjBczxldCOTMe2:b-al2hib) ([raw file](https://github.com/cockroachdb/roachprod/blob/9b2344f9ca93b373d65a830609ce17cfca6afd67/main.go#L761)):*
> ```Go
> of IDs. For example:
> 
>     roachperf marc-test:1-3,8-9 <command>
> ```

`roachprod <command> marc-test:1-3,8-9`

---

*[README.md, line 148 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/26#-L3oDD5clOJBs_C093q-:-L3oDD5clOJBs_C093q0:b5uwaz1) ([raw file](https://github.com/cockroachdb/roachprod/blob/9b2344f9ca93b373d65a830609ce17cfca6afd67/README.md#L148)):*
> ```Markdown
> * Ease the creation of test metadata and then running a series of tests
>   using `roachperf <cluster> test <dir1> <dir2> ...`. Perhaps something like
>   `cockroach prepare <test> <binary>`.
> ```

`s/roachperf/roachprod/`, `s/cockroach/roachprod/g`

---

*[README.md, line 157 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/26#-L3oDHQCEnGnUeLLU4vZ:-L3oDHQCEnGnUeLLU4v_:b-dp5tf7) ([raw file](https://github.com/cockroachdb/roachprod/blob/9b2344f9ca93b373d65a830609ce17cfca6afd67/README.md#L157)):*
> ```Markdown
> 
> * Configure and run haproxy. (Assume it is already installed). This can be
>   done by running "cockroach gen haproxy" after the cluster is started.
> ```

I think this can be deleted now that certain load generators such as `kv` can talk to multiple nodes.

---

*[README.md, line 161 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/26#-L3oDP0F6oKQflrryhvi:-L3oDP0F6oKQflrryhvj:bhofei7) ([raw file](https://github.com/cockroachdb/roachprod/blob/9b2344f9ca93b373d65a830609ce17cfca6afd67/README.md#L161)):*
> ```Markdown
> [cockroach-ephemeral]: https://console.cloud.google.com/home/dashboard?project=cockroach-ephemeral
> [gcloud installed]: https://cloud.google.com/sdk/downloads
> [roachperf]: https://github.com/cockroachdb/roachperf
> ```

Delete?

---

*[ci/nightly.sh, line 3 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/26#-L3oDZtkTn2yxlCYtT7z:-L3oDZtkTn2yxlCYtT8-:b4j6zxa) ([raw file](https://github.com/cockroachdb/roachprod/blob/9b2344f9ca93b373d65a830609ce17cfca6afd67/ci/nightly.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> go install
> ```

Are you going to set up the teamcity job which runs this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/roachprod/26#-:-L3oDlunqCTzIMOkObdL:b-lmzxxp)*

**Comment by benesch** [comment]
Review status: 0 of 19 files reviewed at latest revision, 7 unresolved discussions.

---

*[cassandra.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/26#-L3oCSB8WRMxEOppKFDL:-L3oGYIiX5bHocYg3ClF:b-896fix) ([raw file](https://github.com/cockroachdb/roachprod/blob/9b2344f9ca93b373d65a830609ce17cfca6afd67/cassandra.go#L80)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I noticed after submitting that this breaks `roachprod status local`. Can you just delete this line?
</blockquote></details>

Done.

---

*[main.go, line 562 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/26#-L3oCh_DWXIFhFphRHZE:-L3oGo_MotXM0l0bBkaI:b-896fix) ([raw file](https://github.com/cockroachdb/roachprod/blob/9b2344f9ca93b373d65a830609ce17cfca6afd67/main.go#L562)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/denim test/test denim/g`
</blockquote></details>

Done.

---

*[main.go, line 761 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/26#-L3oCvCik9AWJpfs2weC:-L3oH1LFgIUV04GxErK6:b-u5ckhe) ([raw file](https://github.com/cockroachdb/roachprod/blob/9b2344f9ca93b373d65a830609ce17cfca6afd67/main.go#L761)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`roachprod <command> marc-test:1-3,8-9`
</blockquote></details>

Thanks, done. (With a little added sugar to automatically determine what `<command>` is.)

---

*[README.md, line 148 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/26#-L3oDD5clOJBs_C093q-:-L3oH9qaN_8ymoOc42fp:b-896fix) ([raw file](https://github.com/cockroachdb/roachprod/blob/9b2344f9ca93b373d65a830609ce17cfca6afd67/README.md#L148)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/roachperf/roachprod/`, `s/cockroach/roachprod/g`
</blockquote></details>

Done.

---

*[README.md, line 157 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/26#-L3oDHQCEnGnUeLLU4vZ:-L3oHBVShLgHTKveI-sF:b-896fix) ([raw file](https://github.com/cockroachdb/roachprod/blob/9b2344f9ca93b373d65a830609ce17cfca6afd67/README.md#L157)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think this can be deleted now that certain load generators such as `kv` can talk to multiple nodes.
</blockquote></details>

Done.

---

*[README.md, line 161 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/26#-L3oDP0F6oKQflrryhvi:-L3oHJ3ca2hhHtZzQMHp:b-896fix) ([raw file](https://github.com/cockroachdb/roachprod/blob/9b2344f9ca93b373d65a830609ce17cfca6afd67/README.md#L161)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Delete?
</blockquote></details>

Done.

---

*[ci/nightly.sh, line 3 at r1](https://reviewable.io:443/reviews/cockroachdb/roachprod/26#-L3oDZtkTn2yxlCYtT7z:-L3oHKkO1yQFCvJqXlq4:b17iufp) ([raw file](https://github.com/cockroachdb/roachprod/blob/9b2344f9ca93b373d65a830609ce17cfca6afd67/ci/nightly.sh#L3)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Are you going to set up the teamcity job which runs this?
</blockquote></details>

Yep, seems to be working: https://teamcity.cockroachdb.com/viewLog.html?buildId=494599&buildTypeId=Cockroach_Nightlies_RoachprodNightly&tab=buildLog&_focus=363

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/roachprod/26)*

**Comment by petermattis** [comment]
:shipit:

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/roachprod/26#-:-L3oR1gIOz3TbOXx7QaC:b-xr9eiq)*

**Comment by benesch** [comment]
TFTR!

**Pull request merged**
